# Generated by Django 3.2.9 on 2021-11-25 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_alter_productos_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='cantidad',
            field=models.IntegerField(default=0),
        ),
    ]
